[package]
name = "ucan"
description = "Implement UCAN-based authorization with conciseness and ease!"
keywords = ["ucan", "authz", "jwt", "pki"]
categories = [
  "authentication",
  "cryptography",
  "encoding",
  "web-programming"
]
documentation = "https://docs.rs/ucan"
repository = "https://github.com/cdata/rs-ucan/"
homepage = "https://github.com/cdata/rs-ucan"
license = "Apache-2.0"
readme = "README.md"
version = "0.5.0"
edition = "2021"

[features]
default = []

[dependencies]
anyhow = "1.0"
async-recursion = "1.0"
async-trait = "0.1"
base64 = "0.22"
bs58 = "0.5"
cid = { version = "0.11", features = ["serde"] }
futures = "0.3"
instant = { version = "0.1", features = ["wasm-bindgen"] }
libipld-core = { version = "0.16", features = ["serde-codec", "serde"] }
libipld-json = "0.16"
log = "0.4"
multihash-codetable = { version = "0.1", features = ["sha2", "blake3", "blake2b"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
unsigned-varint = "0.8"
url = "2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# NOTE: This is needed so that rand can be included in WASM builds
getrandom = { version = "~0.2", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "^1", features = ["macros", "test-util"] }

[dev-dependencies]
did-key = "0.2"
serde_ipld_dagcbor = "0.6"
wasm-bindgen-test = "0.3"
